#!/bin/sh

#set -x

refresh()
{

cat <<END 
:T:                                System Monitor  
:B: `date`  -- Control-C for stop 
END

lab=20
fmt="%${lab}s  %s"

# collect data

#- system
set -- `cat /proc/meminfo`
shift 7
tot=$1; fr=$3
set -- `cat /proc/meminfo | grep SwapTotal`
swap="$2 $3"


echo "- System"
echo
printf "$fmt" "MEM TOT:" "$tot bytes"	
echo
printf "$fmt" "MEM FREE:" "$fr bytes"	
echo
printf "$fmt" SWAP: "$swap"	
echo
printf "$fmt" CPU: `cat /proc/stat|grep cpu| sed s/cpu//`
echo
printf "$fmt" LOADAVG: "`cat /proc/loadavg`"
echo
printf "$fmt" UPTIME: "`cat /proc/uptime`"
echo

set -- `cat /proc/stat| grep processes`
printf "$fmt" "PROCESSES #:" $2 
echo
echo
echo "- Network"
echo

set -- `cat /proc/net/dev |  sed -n /dummy:/!P | sed -n /:/P` 

while [ $# -gt 0 ]; do
printf "%${lab}s  Tx: %4s Rx: %4s" $1 $2 $7
echo
shift 12
done


kill -10 $pid 2>/dev/null
}

pid=$2
set -- $1

refresh > /tmp/cnt

if [ -z "$1" ] ; then
exec muless -r 2 -e $0 /tmp/cnt
fi

